version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "KafkaProducerLambda-App"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1puc2fj0kaa0i"
s3_prefix = "KafkaProducerLambda-App"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
