AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  KafkaProducerLambda

  Sample SAM Template for KafkaProducerLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  KafkaProducerLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: KafkaProducerLambda
      Handler: com.skaria.aws.kafka.producer.KafkaProducerLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          KAFKA_BROKER_LIST: ip-10-0-131-124.eu-west-2.compute.internal:9092
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        KafkaProducerEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /send
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  KafkaProducerApi:
    Description: "API Gateway endpoint URL for Prod stage for KafkaProducerLambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send/"
  KafkaProducerLambda:
    Description: "KafkaProducerLambda Function ARN"
    Value: !GetAtt KafkaProducerLambda.Arn
  KafkaProducerLambdaIamRole:
    Description: "Implicit IAM Role created for KafkaProducerLambda function"
    Value: !GetAtt KafkaProducerLambda.Arn
